# Generated by Django 4.2 on 2026-04-14 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0005_add_tenant_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(max_length=20)),
                ('secondary_color', models.CharField(max_length=20)),
                ('font_family', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('banner_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_config', to='stores.store')),
                ('theme_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_theme_configs', to='themes.themetemplate')),
            ],
        ),
    ]
