# Generated by Django 4.2 on 2026-04-14 06:00

from django.db import migrations


def seed_theme_templates(apps, schema_editor):
    ThemeTemplate = apps.get_model("themes", "ThemeTemplate")

    templates = [
        {
            "name": "Modern",
            "description": "A clean contemporary storefront theme for general-purpose shops.",
        },
        {
            "name": "Minimal",
            "description": "A simple low-distraction theme focused on clarity and product visibility.",
        },
        {
            "name": "Classic",
            "description": "A familiar traditional storefront theme with a balanced presentation style.",
        },
    ]

    for template in templates:
        ThemeTemplate.objects.get_or_create(
            name=template["name"],
            defaults={"description": template["description"]},
        )


def unseed_theme_templates(apps, schema_editor):
    ThemeTemplate = apps.get_model("themes", "ThemeTemplate")
    ThemeTemplate.objects.filter(
        name__in=["Modern", "Minimal", "Classic"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("themes", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_theme_templates, unseed_theme_templates),
    ]
