# Generated by Django 4.2 on 2026-04-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tenant_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Tenant ID for multi-tenant isolation', null=True),
        ),
    ]
