# Generated by Django 6.0.3 on 2026-04-08 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('stores', '0005_add_tenant_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Product description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('sku', models.CharField(help_text='Stock Keeping Unit (unique per store)', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Product status (active/inactive)', max_length=20)),
                ('tenant_id', models.IntegerField(db_index=True, help_text='Tenant ID for multi-tenant isolation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Product creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Product last update timestamp')),
                ('category', models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category')),
                ('store', models.ForeignKey(help_text='Store this product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current stock quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Inventory creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Inventory last update timestamp')),
                ('product', models.OneToOneField(help_text='Product this inventory belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(help_text='Image URL/path')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Image upload timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Image last update timestamp')),
                ('product', models.ForeignKey(help_text='Product this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id'], name='products_pr_tenant__7a789b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', 'store'], name='products_pr_tenant__bd1957_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'sku'], name='products_pr_store_i_7783de_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'sku')},
        ),
    ]
