# Generated by Django 6.0.3 on 2026-04-08 17:28

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Uploaded product image file', null=True, upload_to=products.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Image URL/path'),
        ),
    ]
