# Generated by Django 4.2 on 2026-04-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_image_file_alter_productimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('out_of_stock', 'Out of Stock')], default='active', help_text='Product status (active/draft/out_of_stock)', max_length=20),
        ),
    ]
