# Generated by Django 4.2 on 2026-04-07 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0005_add_tenant_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, help_text='Tenant ID for multi-tenant isolation', null=True)),
                ('name', models.CharField(help_text='Category name (unique within store)', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional category description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when category was last updated')),
                ('store', models.ForeignKey(help_text='Store this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='stores.store')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant_id'], name='categories__tenant__b749eb_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['store'], name='categories__store_i_f05b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant_id', 'store'], name='categories__tenant__f50e95_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['store', 'name'], name='categories__store_i_e4d1b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('store', 'name')},
        ),
    ]
