export { default as MarketingHomePage } from './screens/MarketingHomePage'
export { default as StorefrontHomePage } from './screens/StorefrontHomePage'
export { default as ProductListingPage } from './screens/ProductListingPage'
export { default as CategoryListingPage } from './screens/CategoryListingPage'
export { default as CategoryDetailsPage } from './screens/CategoryDetailsPage'
export { default as ProductDetailsPage } from './screens/ProductDetailsPage'
export { default as CartPage } from './screens/CartPage'
export { default as CheckoutPage } from './screens/CheckoutPage'
export { default as CustomerLoginPage } from './screens/CustomerLoginPage'
export { default as CustomerRegisterPage } from './screens/CustomerRegisterPage'
export { default as CustomerAccountDashboardPage } from './screens/CustomerAccountDashboardPage'
export { default as CustomerProfilePage } from './screens/CustomerProfilePage'
export { default as CustomerAddressesPage } from './screens/CustomerAddressesPage'
export { default as CustomerOrdersPage } from './screens/CustomerOrdersPage'
export { default as CustomerOrderDetailsPage } from './screens/CustomerOrderDetailsPage'
export { PolicyContentPage, StaticContentPage } from './screens/StaticContentPage'
