# Generated by Django 4.2 on 2026-04-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_storedomain_storesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='tenant_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['tenant_id'], name='stores_stor_tenant__cfc0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['tenant_id', 'slug'], name='stores_stor_tenant__f32c53_idx'),
        ),
    ]
