# Generated by Django 6.0.3 on 2026-04-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_add_tenant_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('setup', 'Setup'), ('active', 'Active'), ('inactive', 'Inactive')], default='setup', max_length=20),
        ),
    ]
