# Generated by Django 6.0.3 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0006_alter_store_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("setup", "Setup"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                ],
                default="setup",
                max_length=20,
            ),
        ),
    ]

