# Generated by Django 4.2 on 2026-04-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_alter_store_status_add_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='subdomain',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
